name: CASE-Implementation-PyPI-Pillow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

defaults:
  run:
    working-directory: ./

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      with:
        max_line_length: 90

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv development
        . development/bin/activate
        python -m pip install --upgrade pip
        python -m pip install pylint pytest rdflib
        python setup.py install
        pillow2case --help
  
    - name: Pre-commit Checks
      run: |
        pip -q install pre-commit
        pre-commit run --all-files

    - name: Lint with pylint
      run: |
        . development/bin/activate
        pylint --exit-zero *.py */*.py

    # Run the CASE validation job to confirm all examples in pillow_output_examples are valid
    - name: CASE Export Validation
      uses: kchason/case-validation-action@v2.6
      with:
        case-path: ./pillow_output_examples/
        case-version: "case-1.2.0"
        extension-filter: "json"
